[TOC]

# ES使用过程中的异常及解决方案

## 1. 连接超时

```python
ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
```

解决办法：

```python
client = Elasticsearch(['http://localhost:9200/'],timeout=60, max_retries=10, retry_on_timeout=True)
```

## 2. 配置同义词时出现问题

[参考如下问题](https://discuss.elastic.co/t/synonym-token-filter-error/160016)

```python
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'failed to build synonyms')
```

```json
"jieba_synonym": {
    "type": "synonym",
    "synonyms_path": "synonyms/synonyms.txt",
    "lenient": True //解决问题的关键在于添加这个
}
```
